### PR TITLE
Much better .gitattributes .gitignore

### PR DESCRIPTION
**Pull request by ALIENQuake**
Those files are best practices based on years of corrections, addition and merging ideas from various sources.

### CODE REVIEW

**Review by Sampsca — COMMENTED** [review]
I have a significant number of comments.

## .gitattributes

> `# use export-ignore to skip files when downloading`
> `**/.* export-ignore`

I don't understand what this is for.

---
> *.gitignore text eol=crlf
> *.gitattributes text eol=crlf
> *.y[a]ml text eol=crlf

I feel that anyone cloning a local copy of a repo would strongly desire these files to be in their native encoding.  Why is this more desirable than simply using:
```
*.gitignore text
*.gitattributes text
*.y[a]ml text
```

---
.gitattributes includes
> *.bat text eol=crlf

but then in .gitignore you have
> *.bat

Why would you specify an eol for a file type you turn around and ignore?

---
> *.csv text eol=crlf

Comma Separated Values (CSV) files are just plain text files with columns of data separated by commas, and rows separated by the eol character.  Again, I feel that anyone cloning a local copy of a repo would strongly desire these files to be in their native encoding.  Why is this more desirable than simply using:
```
*.csv text
```
The same question applies to
> *.ini text eol=crlf
> *.txt text eol=crlf

---
> *.ps1 text eol=crlf

If this is a PowerShell script, aren't recent versions of PowerShell cross-platform?  If so, wouldn't the above argument apply?

---
I think I'm okay with these
> *.command text eol=lf
> *.sh text eol=lf

---
git is usually very good about determining whether a file is binary or text.  Only very rarely is it explicitly necessary to specify.  That being the case, are these really necessary?
> *.7z binary
> *.bmp binary
> *.dll binary
> *.eff binary
> *.exe binary
> *.gif binary
> *.htm[l] text
> *.ico binary
> *.jpg binary
> *.png binary
> 
> 
> *.2da text
> *.are binary
> *.baf text
> *.bam binary
> *.cre binary
> *.d text
> *.dlg binary
> *.ids text
> *.itm binary
> *.mos binary
> *.plt binary
> *.pro binary
> *.pvrz binary
> *.spl binary
> *.sto binary
> *.tp2 text
> *.tpa text
> *.tph text
> *.tpp text
> *.tra text
> *.vef binary
> *.vvc binary
> *.wav binary
> *.wed binary
> *.wmp binary

If they are, in fact, arguably necessary, you're missing a good number of IE file formats.

---
> *.bcs text eol=lf

I have seen compelling arguments for using both this and binary here.  I lean toward text eol=lf, but in either case, you are missing *.bs.

---
## .gitignore

> `- ehthumbs.db`
> `- ehthumbs_vista.db`

I see no reason to remove these.

---
> `+ temp/`
> `+ tmp/`

I can see how some modding styles could benefit from this.  However, I can also see this being dangerous (having unintended effects) if this .gitignore file is marketed at a best-practace dorp-in configuration for modders new to git who aren't observant or who don't have a firm understanding of what this file is for.

---
> `- *.ahk`

I added this on purpose because of how my working directory is set up.

---
> `+ .*`

Again, this seems arbitrary to me, and I can foresee it having unexpected consequences for the unwary.  What's the rationale for it?

---
> `+ backup/`

in conjunction with deleting `BGEEClassicMovies/backup/.gitignore`
I don't like this, mostly for personal reasons.  I remember when WeiDU had issues with destination folders (including the BACKUP folder) that did not already explicitly exit.  Back in the day, it was best practice to explicitly include a BACKUP folder in your mod's archive.  As some ZIP/RAR archive programs wouldn't store/extract empty folders, many modders went the extra step and added a simple text file to the BACKUP folder to ensure it was created.  Something like "reserved.txt" with "reserved" as its contents (although the specifics varied from modder to modder).  Similarly, git does not store empty folders.  To get around this, the most elegant solution I have found is to add a .gitignore file to the BACKUP folder which tells git to ignore any other contents in that folder.

I recognize that recent versions of WeiDU are no longer effected by this restriction, but the idea of ignoring such an ingrained best-practice leaves me with a bad taste in my mouth.

**Comment by ALIENQuake** [comment]
@Sampsca 
Hi,

>**/.* export-ignore

It means that whenever somebody will download the repository source code az zip, all files with a dot at the beginning will not be added to Sampsca-BGEE-Classic-Movies-master.zip. This is handly to avoid questions from 'Windows Explorer' about .gitignore already exist, overwrite?

> *.ahk

Sure, restored back.

> .*

Files with a dot at the beginning at the top-level of the repo are ignored except explicitly specified. It also covers macOS `.DS_Store crap`

> Why would you specify an eol for a file type you turn around and ignore?

Because some modders added one single .bat explicitly. All other test.bat files are ignored.


> > ehthumbs.db
> > ehthumbs_vista.db
> 
> I see no reason to remove these.

Those are simply redundant in 2020. Those files are created only when someone who develops mod has Vista (<0.8% marketshare) and open the mod directory via it's Media Center.

> > temp/
> > tmp/
> I can see how some modding styles could benefit from this. However, I can also see this being dangerous (having unintended effects) if this .gitignore file is marketed at a best-practace dorp-in configuration for modders new to git who aren't observant or who don't have a firm understanding of what this file is for.

I don't have much to say about this except no 'temp' files or directories should end up inside packages of any kind.

> *.bcs text eol=lf
> 
> I have seen compelling arguments for using both this and binary here. I lean toward text eol=lf, but in either case, you are missing *.bs.
Confirmed by EE devs and real use-case, the only thing which is required is LF. Added *.bs.

> git is usually very good about determining whether a file is binary or text. Only very rarely is it explicitly necessary to specify. That being the case, are these really necessary?
> If they are, in fact, arguably necessary, you're missing a good number of IE file formats.

Including those will protect from git changes that might be introduced later. If there are missing formats, please add them.

> *.ini text eol=crlf
> *.txt text eol=crlf

Those are windows-native files. Image readme.txt created as CRLF, uploaded to git and then open via Windows 7 Notepad => file looks malformed.

> *.csv text eol=crlf
> *.ps1 text eol=crlf
I guess those can be either removed completly or replaced with 'text', you call.

> *.gitignore text
> *.gitattributes text
> *.y[a]ml text

Agreed, don't have strong opinion on this.

> backup/
> I recognize that recent versions of WeiDU are no longer effected by this restriction
That's the point. If WeiDU handles the creation of the 'backup' directory correctly, there is no reason to using a sophisticated trick in order to 'ensure that WeiDU is not broken'.

I hope that things are clear now. I think that the best way now is to reject this PR and take only the parts which you desire. Or accept it and make further corrections. In any case, I will take your concerns into consideration when I will update my .git* files template.

**Comment by Sampsca** [comment]
> ```
> *.ini text eol=crlf
> *.txt text eol=crlf
> ```
> 
> Those are windows-native files. Image readme.txt created as CRLF, uploaded to git and then open via Windows 7 Notepad => file looks malformed.
Regardless of which OS first used these file extensions, mods are now using them to allow users fine control over mod component installations rather than using READLN.  See [Infinity Animations](https://github.com/GwendolyneFreddy/Infinity-Animations#warning-warning-new-installation-process) for example.  Users will want them to be in their native encoding.  If eol is left unspecified, git should handle the eol conversions to a user's native convention automatically, correct?  Unless someone has specifically configured git otherwise, I know eols are automatically adjusted when cloning a repo onto your local system, but I thought it did a similar thing when downloading releases as well.

**Comment by ALIENQuake** [comment]
> > ```
> > *.ini text eol=crlf
> > *.txt text eol=crlf
> > ```
> > 
> > 
> > Those are windows-native files. Image readme.txt created as CRLF, uploaded to git and then open via Windows 7 Notepad => file looks malformed.
> 
> Regardless of which OS first used these file extensions, mods are now using them to allow users fine control over mod component installations rather than using READLN. See [Infinity Animations](https://github.com/GwendolyneFreddy/Infinity-Animations#warning-warning-new-installation-process) for example. Users will want them to be in their native encoding. If eol is left unspecified, git should handle the eol conversions to a user's native convention automatically, correct? Unless someone has specifically configured git otherwise, I know eols are automatically adjusted when cloning a repo onto your local system, but I thought it did a similar thing when downloading releases as well.

Git handles eol conversion but only for its basic operation like pull/push, not for GitHub-related hosting features like 
'downloading repo as zip'. On default git configuration, when you have local readme.txt/config.ini with CRLF, after pushing into online repo, CRLF will be replaced into LF. Then, when you downloading mod via 'Source code' you will get direct files from the repo => .txt/.ini files with LF that makes them unreadable on Windows. So that eol=crlf is required.

**Comment by ALIENQuake** [comment]
Found that .csv actually use [RFC 4180](https://tools.ietf.org/html/rfc4180#section-2) and Excel expects them to be CRLF.

**Comment by Sampsca** [comment]
I manually adjusted .gitattributes and .gitignore based on your suggestions.  Also added more IE file formats.

**Pull request closed without merging**
